// Code generated by authara-sdk-gen from authara-core/contract/openapi.yaml; DO NOT EDIT.

package authara

import (
	"time"

	"github.com/google/uuid"
)

type APIAPIError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type APIAuthSession struct {
	AccessToken  string      `json:"access_token"`
	RefreshToken string      `json:"refresh_token"`
	User         APIAuthUser `json:"user"`
}

type APIAuthUser struct {
	CreatedAt time.Time `json:"created_at"`
	Disabled  bool      `json:"disabled"`
	Email     string    `json:"email"`
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
}

type APICSRFToken struct {
	CSRFToken string `json:"csrf_token"`
}

type APICapabilities struct {
	AllowsInvitations                  bool   `json:"allows_invitations"`
	AllowsOrgSwitching                 bool   `json:"allows_org_switching"`
	AllowsOrganizationLeave            bool   `json:"allows_organization_leave"`
	AllowsPublicOrganizationManagement bool   `json:"allows_public_organization_management"`
	AllowsUserCreatedTeamOrgs          bool   `json:"allows_user_created_team_orgs"`
	HasVisibleOrganizations            bool   `json:"has_visible_organizations"`
	OrganizationMode                   string `json:"organization_mode"`
}

type APIChallengeReference struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
}

type APICurrentOrganizationMember struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     string              `json:"email"`
	Role      APIOrganizationRole `json:"role"`
	UserID    uuid.UUID           `json:"user_id"`
	Username  string              `json:"username"`
}

type APICurrentOrganizationMembers struct {
	Members []APICurrentOrganizationMember `json:"members"`
}

type APICurrentUser struct {
	CreatedAt    time.Time              `json:"created_at"`
	Disabled     bool                   `json:"disabled"`
	Email        string                 `json:"email"`
	ID           uuid.UUID              `json:"id"`
	Organization APIOrganizationSummary `json:"organization"`
	Roles        []string               `json:"roles"`
	Username     string                 `json:"username"`
}

type APIErrorResponse struct {
	Error APIAPIError `json:"error"`
}

type APIGoogleLoginOptions struct {
	ClientID string `json:"client_id"`
	Nonce    string `json:"nonce"`
}

type APIGoogleLoginRequest struct {
	Credential string `json:"credential"`
	Nonce      string `json:"nonce"`
}

type APIInternalCreateInvitationRequest struct {
	ActorUserID uuid.UUID `json:"actor_user_id"`
	Email       string    `json:"email"`
}

type APIInternalCreateOrganizationRequest struct {
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
	Name            string    `json:"name"`
}

type APIMembership struct {
	CreatedAt      time.Time           `json:"created_at"`
	OrganizationID uuid.UUID           `json:"organization_id"`
	Role           APIOrganizationRole `json:"role"`
	UpdatedAt      time.Time           `json:"updated_at"`
	UserID         uuid.UUID           `json:"user_id"`
}

type APIMembershipWithOrganization struct {
	Membership   APIMembership   `json:"membership"`
	Organization APIOrganization `json:"organization"`
}

type APIOrganization struct {
	CreatedAt       time.Time  `json:"created_at"`
	CreatedByUserID *uuid.UUID `json:"created_by_user_id,omitempty"`
	ID              uuid.UUID  `json:"id"`
	Kind            string     `json:"kind"`
	Name            string     `json:"name"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type APIOrganizationEnvelope struct {
	Organization APIOrganization `json:"organization"`
}

type APIOrganizationInvitation struct {
	Email          string              `json:"email"`
	ExpiresAt      time.Time           `json:"expires_at"`
	ID             uuid.UUID           `json:"id"`
	InviteURL      *string             `json:"invite_url,omitempty"`
	OrganizationID uuid.UUID           `json:"organization_id"`
	Role           APIOrganizationRole `json:"role"`
	Status         string              `json:"status"`
}

type APIOrganizationInvitationEnvelope struct {
	Invitation APIOrganizationInvitation `json:"invitation"`
}

type APIOrganizationInvitations struct {
	Invitations []APIOrganizationInvitation `json:"invitations"`
}

type APIOrganizationMember struct {
	CreatedAt      time.Time           `json:"created_at"`
	Disabled       bool                `json:"disabled"`
	Email          string              `json:"email"`
	OrganizationID uuid.UUID           `json:"organization_id"`
	Role           APIOrganizationRole `json:"role"`
	UpdatedAt      time.Time           `json:"updated_at"`
	UserID         uuid.UUID           `json:"user_id"`
	Username       string              `json:"username"`
}

type APIOrganizationMemberEnvelope struct {
	Member APIOrganizationMember `json:"member"`
}

type APIOrganizationMembers struct {
	Members []APIOrganizationMember `json:"members"`
}

type APIOrganizationRole string

type APIOrganizationSummaries struct {
	Organizations []APIOrganizationSummary `json:"organizations"`
}

type APIOrganizationSummary struct {
	ID   uuid.UUID           `json:"id"`
	Name string              `json:"name"`
	Role APIOrganizationRole `json:"role"`
}

type APIOrganizationWithMembership struct {
	Membership   APIMembership   `json:"membership"`
	Organization APIOrganization `json:"organization"`
}

type APIPasskeyAuthenticationFinishRequest struct {
	ChallengeID uuid.UUID      `json:"challenge_id"`
	Credential  map[string]any `json:"credential"`
}

type APIPasskeyOptions struct {
	ChallengeID uuid.UUID      `json:"challenge_id"`
	Options     map[string]any `json:"options"`
}

type APIPasskeyRegistrationFinishRequest struct {
	ChallengeID  uuid.UUID      `json:"challenge_id"`
	Credential   map[string]any `json:"credential"`
	Name         *string        `json:"name,omitempty"`
	PlatformHint *string        `json:"platform_hint,omitempty"`
}

type APIPasswordLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type APIRevokeInvitationRequest struct {
	RevokedByUserID *uuid.UUID `json:"revoked_by_user_id,omitempty"`
}

type APISignupChallenge struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
}

type APISignupChallengeVerification struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
	Code        string    `json:"code"`
}

type APISignupRequest struct {
	Email          string  `json:"email"`
	InvitationCode *string `json:"invitation_code,omitempty"`
	Password       string  `json:"password"`
}

type APITokenRefreshRequest struct {
	Audience     *string `json:"audience,omitempty"`
	RefreshToken string  `json:"refresh_token"`
}

type APITokens struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type APIUpdateOrganizationRequest struct {
	Name string `json:"name"`
}

type APIUserMemberships struct {
	Memberships []APIMembershipWithOrganization `json:"memberships"`
}

const APIAppAudienceApp = "app"

const APIAudienceAdmin = "admin"

const APIAudienceApp = "app"

const APICapabilitiesOrganizationModeMulti = "multi"

const APICapabilitiesOrganizationModePersonal = "personal"

const APICapabilitiesOrganizationModeSingle = "single"

const APICurrentUserRolesItemAutharaAdmin = "authara:admin"

const APICurrentUserRolesItemAutharaAuditor = "authara:auditor"

const APICurrentUserRolesItemAutharaMonitor = "authara:monitor"

const APIFinishPasskeyAuthenticationAudienceAdmin = "admin"

const APIFinishPasskeyAuthenticationAudienceApp = "app"

const APILoginWithGoogleAudienceAdmin = "admin"

const APILoginWithGoogleAudienceApp = "app"

const APILoginWithPasswordAudienceAdmin = "admin"

const APILoginWithPasswordAudienceApp = "app"

const APIOrganizationInvitationStatusAccepted = "accepted"

const APIOrganizationInvitationStatusExpired = "expired"

const APIOrganizationInvitationStatusPending = "pending"

const APIOrganizationInvitationStatusRevoked = "revoked"

const APIOrganizationKindPersonal = "personal"

const APIOrganizationKindTeam = "team"

const APIOrganizationRoleAdmin APIOrganizationRole = "admin"

const APIOrganizationRoleMember APIOrganizationRole = "member"

const APIOrganizationRoleOwner APIOrganizationRole = "owner"

const APIRefreshSessionAudienceAdmin = "admin"

const APIRefreshSessionAudienceApp = "app"

const APISignupDirectAudienceApp = "app"

const APIStartSignupChallengeAudienceApp = "app"

const APISwitchOrganizationAudienceAdmin = "admin"

const APISwitchOrganizationAudienceApp = "app"

const APITokenRefreshRequestAudienceAdmin = "admin"

const APITokenRefreshRequestAudienceApp = "app"

const APIVerifySignupChallengeAudienceApp = "app"
