// Code generated by authara-sdk-gen from authara-core/contract/openapi.yaml; DO NOT EDIT.

package authara

import (
	"context"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

func apiRequestOptions(incoming *http.Request, cookies []string, csrf bool) []requestOption {
	var opts []requestOption
	if len(cookies) > 0 {
		opts = append(opts, func(req *http.Request) {
			if incoming == nil {
				return
			}
			for _, name := range cookies {
				if cookie, err := incoming.Cookie(name); err == nil {
					req.AddCookie(cookie)
				}
			}
		})
	}
	if csrf {
		if token, ok := CSRFToken(incoming); ok {
			opts = append(opts, withCSRFToken(token))
		}
	}
	return opts
}

func (c *Client) CallGetPublicCapabilities(ctx context.Context, incoming *http.Request) (*APICapabilities, error) {
	var out APICapabilities
	path := "/auth/api/v1/capabilities"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallResendChallenge(ctx context.Context, incoming *http.Request, body APIChallengeReference) error {
	path := "/auth/api/v1/challenges/resend"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallGetCSRFToken(ctx context.Context) (*APICSRFToken, error) {
	var out APICSRFToken
	path := "/auth/api/v1/csrf"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallLoginWithPassword(ctx context.Context, incoming *http.Request, audience string, body APIPasswordLoginRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/login"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallLoginWithGoogle(ctx context.Context, incoming *http.Request, audience string, body APIGoogleLoginRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/oauth/google"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf", "authara_oauth_nonce"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetGoogleLoginOptions(ctx context.Context) (*APIGoogleLoginOptions, error) {
	var out APIGoogleLoginOptions
	path := "/auth/api/v1/oauth/google/options"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallListCurrentUserOrganizations(ctx context.Context, incoming *http.Request) (*APIOrganizationSummaries, error) {
	var out APIOrganizationSummaries
	path := "/auth/api/v1/organizations"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetCurrentOrganization(ctx context.Context, incoming *http.Request) (*APIOrganizationSummary, error) {
	var out APIOrganizationSummary
	path := "/auth/api/v1/organizations/current"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallListCurrentOrganizationMembers(ctx context.Context, incoming *http.Request) (*APICurrentOrganizationMembers, error) {
	var out APICurrentOrganizationMembers
	path := "/auth/api/v1/organizations/current/members"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetPublicOrganization(ctx context.Context, incoming *http.Request, organizationID uuid.UUID) (*APIOrganizationEnvelope, error) {
	var out APIOrganizationEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallUpdatePublicOrganization(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, body APIUpdateOrganizationRequest) (*APIOrganizationEnvelope, error) {
	var out APIOrganizationEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodPatch, path, body, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallListPublicOrganizationInvitations(ctx context.Context, incoming *http.Request, organizationID uuid.UUID) (*APIOrganizationInvitations, error) {
	var out APIOrganizationInvitations
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetPublicOrganizationInvitation(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, invitationID uuid.UUID) (*APIOrganizationInvitationEnvelope, error) {
	var out APIOrganizationInvitationEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations/" + url.PathEscape(invitationID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallRevokePublicOrganizationInvitation(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, invitationID uuid.UUID) (*APIOrganizationInvitationEnvelope, error) {
	var out APIOrganizationInvitationEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations/" + url.PathEscape(invitationID.String()) + "/revoke"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallListPublicOrganizationMembers(ctx context.Context, incoming *http.Request, organizationID uuid.UUID) (*APIOrganizationMembers, error) {
	var out APIOrganizationMembers
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/members"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetPublicOrganizationMember(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, userID uuid.UUID) (*APIOrganizationMemberEnvelope, error) {
	var out APIOrganizationMemberEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/members/" + url.PathEscape(userID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallSwitchOrganization(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, audience string) (*APITokens, error) {
	var out APITokens
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/switch"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallFinishPasskeyAuthentication(ctx context.Context, incoming *http.Request, audience string, body APIPasskeyAuthenticationFinishRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/passkeys/authenticate/finish"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallBeginPasskeyAuthentication(ctx context.Context, incoming *http.Request) (*APIPasskeyOptions, error) {
	var out APIPasskeyOptions
	path := "/auth/api/v1/passkeys/authenticate/options"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallFinishPasskeyRegistration(ctx context.Context, incoming *http.Request, body APIPasskeyRegistrationFinishRequest) error {
	path := "/auth/api/v1/passkeys/register/finish"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallBeginPasskeyRegistration(ctx context.Context, incoming *http.Request) (*APIPasskeyOptions, error) {
	var out APIPasskeyOptions
	path := "/auth/api/v1/passkeys/register/options"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallStartPasswordResetChallenge(ctx context.Context, incoming *http.Request, body APIPasswordResetRequest) (*APIChallengeReference, error) {
	var out APIChallengeReference
	path := "/auth/api/v1/password-reset/challenges"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallVerifyPasswordResetChallenge(ctx context.Context, incoming *http.Request, body APIPasswordResetChallengeVerification) error {
	path := "/auth/api/v1/password-reset/challenges/verify"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallLogout(ctx context.Context, incoming *http.Request) error {
	path := "/auth/api/v1/sessions/logout"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, nil, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallRefreshSession(ctx context.Context, incoming *http.Request, audience string) error {
	path := "/auth/api/v1/sessions/refresh"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, nil, apiRequestOptions(incoming, []string{"authara_csrf", "authara_refresh"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallStartSignupChallenge(ctx context.Context, incoming *http.Request, audience string, body APISignupRequest) (*APISignupChallenge, error) {
	var out APISignupChallenge
	path := "/auth/api/v1/signup/challenges"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallVerifySignupChallenge(ctx context.Context, incoming *http.Request, audience string, body APISignupChallengeVerification) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/signup/challenges/verify"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallSignupDirect(ctx context.Context, incoming *http.Request, audience string, body APISignupRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/signup/direct"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallRefreshTokens(ctx context.Context, body APITokenRefreshRequest) (*APITokens, error) {
	var out APITokens
	path := "/auth/api/v1/tokens/refresh"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetCurrentUser(ctx context.Context, incoming *http.Request) (*APICurrentUser, error) {
	var out APICurrentUser
	path := "/auth/api/v1/user"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallSetCurrentUserPassword(ctx context.Context, incoming *http.Request, body APISetPasswordRequest) error {
	path := "/auth/api/v1/users/password"
	_, err := c.doJSONBody(ctx, http.MethodPut, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallListPublicUserMemberships(ctx context.Context, incoming *http.Request, userID uuid.UUID) (*APIUserMemberships, error) {
	var out APIUserMemberships
	path := "/auth/api/v1/users/" + url.PathEscape(userID.String()) + "/memberships"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallCreateInternalOrganization(ctx context.Context, body APIInternalCreateOrganizationRequest) (*APIOrganizationWithMembership, error) {
	var out APIOrganizationWithMembership
	path := "/auth/internal/v1/organizations"
	err := c.internalJSON(ctx, http.MethodPost, path, body, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallCreateInternalOrganizationInvitation(ctx context.Context, organizationID uuid.UUID, body APIInternalCreateInvitationRequest) (*APIOrganizationInvitationEnvelope, error) {
	var out APIOrganizationInvitationEnvelope
	path := "/auth/internal/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations"
	err := c.internalJSON(ctx, http.MethodPost, path, body, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallResendInternalOrganizationInvitation(ctx context.Context, organizationID uuid.UUID, invitationID uuid.UUID) (*APIOrganizationInvitationEnvelope, error) {
	var out APIOrganizationInvitationEnvelope
	path := "/auth/internal/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations/" + url.PathEscape(invitationID.String()) + "/resend"
	err := c.internalJSON(ctx, http.MethodPost, path, nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
