package authara

import (
	"encoding/json"
	"time"
)

// WebhookEvent represents a webhook event sent by Authara.
//
// Each event contains metadata (ID, type, timestamp) and a raw JSON
// payload in Data that can be decoded into a concrete event type.
type WebhookEvent struct {
	// ID is the unique identifier of the webhook event.
	//
	// It can be used for idempotency and deduplication when processing events.
	ID string `json:"id"`

	// Type identifies the type of event (e.g. "user.created").
	//
	// Applications should use this field to determine how to handle the event.
	Type string `json:"type"`

	// CreatedAt is the timestamp when the event was generated by Authara.
	//
	// This can be used for ordering or auditing purposes.
	CreatedAt time.Time `json:"created_at"`

	// Data contains the event-specific payload as raw JSON.
	//
	// It must be decoded into the appropriate struct depending on Type.
	Data json.RawMessage `json:"data"`
}

// UserCreatedData is the payload for the "user.created" event.
//
// It contains information about the newly created user.
type UserCreatedData struct {
	// UserID is the unique identifier of the created user.
	UserID string `json:"user_id"`
}

// UserDeletedData is the payload for the "user.deleted" event.
//
// It contains information about the deleted user.
type UserDeletedData struct {
	// UserID is the unique identifier of the deleted user.
	UserID string `json:"user_id"`
}
