package main

import (
	"errors"
	"fmt"
	"net/http"
	"strings"
	"unicode"
)

func methodConst(method string) string {
	switch method {
	case http.MethodGet:
		return "http.MethodGet"
	case http.MethodPost:
		return "http.MethodPost"
	case http.MethodPatch:
		return "http.MethodPatch"
	case http.MethodPut:
		return "http.MethodPut"
	case http.MethodDelete:
		return "http.MethodDelete"
	default:
		return fmt.Sprintf("%q", method)
	}
}

func (g generator) header() string {
	return "// Code generated by authara-sdk-gen from authara-core/contract/openapi.yaml; DO NOT EDIT.\n\npackage authara\n\n"
}

func apiTypeName(name string) string {
	return "API" + goName(name)
}

func goName(s string) string {
	words := splitIdentifier(s)
	var out strings.Builder
	for _, word := range words {
		lower := strings.ToLower(word)
		if initialism, ok := initialisms[lower]; ok {
			out.WriteString(initialism)
			continue
		}
		out.WriteString(strings.ToUpper(lower[:1]) + lower[1:])
	}
	if out.Len() == 0 {
		panic(errors.New("empty Go identifier"))
	}
	return out.String()
}

func lowerName(s string) string {
	name := goName(s)
	return strings.ToLower(name[:1]) + name[1:]
}

func splitIdentifier(s string) []string {
	var words []string
	for _, segment := range strings.FieldsFunc(s, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	}) {
		runes := []rune(segment)
		start := 0
		for i := 1; i < len(runes); i++ {
			prev := runes[i-1]
			curr := runes[i]
			var next rune
			if i+1 < len(runes) {
				next = runes[i+1]
			}
			split := unicode.IsDigit(prev) != unicode.IsDigit(curr) ||
				(unicode.IsUpper(curr) && (unicode.IsLower(prev) || unicode.IsDigit(prev))) ||
				(unicode.IsUpper(prev) && unicode.IsUpper(curr) && next != 0 && unicode.IsLower(next))
			if split {
				words = append(words, string(runes[start:i]))
				start = i
			}
		}
		words = append(words, string(runes[start:]))
	}
	return words
}

var initialisms = map[string]string{
	"api":   "API",
	"csrf":  "CSRF",
	"id":    "ID",
	"json":  "JSON",
	"oauth": "OAuth",
	"url":   "URL",
}
